### ISSUE TITLE
Butcher Knife recipe should use ore dictionary

### ISSUE THREAD

**Issue by Syndaryl** [CodersDownUnder/SlaughterCraftOriginal#3]
**Is your feature request related to a problem? Please describe.**
I use other mods that provide steel ingots but I can't use them to craft the butcher knife.

**Describe the solution you'd like**
 It would be good to add your steel to the ingotSteel ore dictionary and then have the butcher knife recipe use the ingotSteel entry instead of specifically your ingots.

**Comment by Syndaryl** [comment]
btw your steel ingot icon is very funny :)

**Comment by Trhod17** [comment]
i did add my steel ingot to the ore dict under ingotSteel but forget to tell the recipe to use the oredict Ingotsteel so i was only using butcherymod steelIngot
