### ISSUE TITLE
Early-game butcher knife

### ISSUE THREAD

**Issue by Syndaryl** [CodersDownUnder/SlaughterCraftOriginal#4]
**Is your feature request related to a problem? Please describe.**
Early game, it's not uncommon to find yourself with no food source except animals, depending on your start location and luck. Presuming a default configuration, not being able to butcher animals can be a big problem.

**Describe the solution you'd like**
Add a "flint knife" or "stone knife" for early game butchering - not only should it have lower durability, it should drop less meat. This will encourage upgrading once you can make steel, rather than continually replacing it with another crappy flint knife.

**Describe alternatives you've considered**
Tinkers Construct integration? That's like a whole other mod addon there, though.

**Comment by Trhod17** [comment]
I actually never thought of that
